version: "3.8"

networks:
  npm-nw:
    external: true

services:
  wea-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wea-spring
    environment:
      TZ: "Asia/Seoul"
    restart: always
    networks:
      - npm-nw
    depends_on:
      - wea-mysql
  wea-mysql:
    image: mysql:latest
    container_name: wea-mysql
    environment:
      TZ: "Asia/Seoul"
      MYSQL_USER: weateam
      MYSQL_PASSWORD: weateam0801
      MYSQL_DATABASE: wea
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - /var/wea/db:/var/lib/mysql
    restart: always
