version: "3.8"

networks:
  npm-nw:
    external: true
  backend:
    external: false

services:
  wea-spring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wea-spring
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - /var/wea/server:/var/wea/server
    restart: always
    env_file:
      - ./wea-spring.env
    networks:
      - npm-nw
      - backend
    depends_on:
      - wea-mysql
      - wea-redis
  wea-mysql:
    image: mysql:latest
    container_name: wea-mysql
    environment:
      TZ: "Asia/Seoul"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - /var/wea/db:/var/lib/mysql
    restart: always
    networks:
      - backend
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
  wea-redis:
    image: redis:latest
    container_name: wea-redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - /var/wea/redis:/var/lib/redis/data
    networks:
      - backend
