pipeline {
    agent any

    tools {
        jdk "openjdk-17"
    }

    environment {
        MYSQL_URL = credentials('MYSQL_URL')
        MYSQL_PORT = credentials('MYSQL_PORT')
        MYSQL_USER = credentials('MYSQL_USER')
        MYSQL_PASSWORD = credentials('MYSQL_PASSWORD')
        MYSQL_DATABASE = credentials('MYSQL_DATABASE')
        JWT_SECRET = credentials('JWT_SECRET')
        REDIS_HOST = credentials('REDIS_HOST')
        REDIS_PORT = credentials('REDIS_PORT')
        REDIS_PASSWORD = credentials('REDIS_PASSWORD')
        SMTP_AUTH = 'true'
        SMTP_HOST = 'smtp.naver.com'
        SMTP_PORT = 465
        SMTP_SSL_ENABLE = 'true'
        SMTP_SSL_TRUST = 'smtp.naver.com'
        SMTP_STARTTLS_ENABLE = 'true'
        SMTP_USERNAME = credentials('SMTP_USERNAME')
        TRANSPORT_PROTOCOL = 'smtp'
    }

    stages {
        stage('git-clone') {
            steps {
                git (
                    url: "https://github.com/TeamAnyPayments/anyPayments.git",
                    credentialsId: "mygit",
                    branch: "backend"
                )
            }
        }

        stage('build') {
            steps {
                dir('backend') {
                    sh('chmod +x ./gradlew')
                    sh('./gradlew clean build -x test')
                }
            }
        }

        stage('deploy') {
            steps {
                dir('backend') {
                    sh('/var/jenkins_home/lib/docker-compose config')
                    sh('/var/jenkins_home/lib/docker-compose down')
                    sh('/var/jenkins_home/lib/docker-compose build --no-cache && /var/jenkins_home/lib/docker-compose up -d')
                }
            }
        }
    }

    post {
        success {
            cleanWs()
        }
        failure {
            cleanWs()
        }
    }
}
