pipeline {
    agent any

    tools {
        jdk "openjdk-17"
    }

    environment {
        MYSQL_URL = credentials('MYSQL_URL')
        MYSQL_PORT = 3306
        MYSQL_USER = credentials('MYSQL_USER')
        MYSQL_PASSWORD = credentials('MYSQL_PASSWORD')
        MYSQL_DATABASE = credentials('MYSQL_DATABASE')
        JWT_SECRET = credentials('JWT_SECRET')
    }

    stages {
        stage('git-clone') {
            steps {
                git (
                    url: "https://github.com/TeamAnyPayments/anyPayments.git",
                    credentialsId: "mygit",
                    branch: "backend-jenkins"
                )
            }
        }

        stage('build') {
            steps {
                dir('backend') {
                    sh('chmod +x ./gradlew')
                    sh('./gradlew clean build -x test')
                }
            }
        }

        stage('deploy') {
            steps {
                dir('backend') {
                    sh('/var/jenkins_home/lib/docker-compose config')
                    sh('/var/jenkins_home/lib/docker-compose down')
                    sh('/var/jenkins_home/lib/docker-compose build --no-cache && /var/jenkins_home/lib/docker-compose up -d')
                }
            }
        }
    }

    post {
        success {
            cleanWs()
        }
        failure {
            cleanWs()
        }
    }
}
