pipeline {
    agent any

    tools {
        jdk 'openjdk-17'
    }

    environment {
        NAVER_CLIENT_ID = credentials('NAVER_CLIENT_ID')
        WEBHOOK_URL = credentials('DISCORD_WEBHOOK_URL')
        TOSS_CLIENT_KEY = credentials('TOSS_CLIENT_KEY')
        TOSS_SECRET_KEY = credentials('TOSS_SECRET_KEY')
    }

    stages {

        stage('git-clone') {
            steps {
                git(
                    url: "https://github.com/TeamAnyPayments/anyPayments.git",
                    credentialsId: "mygit",
                    branch: "android"
                )
            }
        }

        stage('build-with-gradle') {
            steps {
                dir ('wea') {
                    sh('echo NAVER_CLIENT_ID=$NAVER_CLIENT_ID > local.properties')
                    sh('echo \n > local.properties')
                    sh('echo TOSS_CLIENT_KEY=$TOSS_CLIENT_KEY > local.properties')
                    sh('echo \n > local.properties')
                    sh('echo TOSS_SECRET_KEY=$TOSS_SECRET_KEY > local.properties')
                    sh('chmod +x gradlew')
                    sh('./gradlew clean assemble') // 일반 APK 빌드
                    // sh('./gradlew clean app:assembleDebug') // DEBUG APK 빌드
                    // sh('./gradlew clean app:assembleRelease') // RELEASE APK 빌드
                }
            }
        }
    }

    post {
            success {
                archiveArtifacts artifacts: '**/*.apk'
                discordSend title: "WE:A 안드로이드 앱 빌드 Job #${env.BUILD_NUMBER}",
                            link: env.BUILD_URL,
                            description: "빌드가 성공했습니다.",
                            thumbnail: 'https://miro.medium.com/v2/resize:fit:640/format:webp/1*cxZhQbf-KuKU_wM8RGgofg.jpeg',
                            enableArtifactsList: true,
                            result: currentBuild.currentResult,
                            webhookURL: env.WEBHOOK_URL
                cleanWs()
            }
            failure {
                discordSend title: "WE:A 안드로이드 앱 빌드 Job #${env.BUILD_NUMBER}",
                            link: env.BUILD_URL,
                            description: "빌드가 실패했습니다. 로그를 확인해주세요.",
                            thumbnail: 'https://www.geeky-gadgets.com/wp-content/uploads/2011/04/Sad-Android.jpg',
                            result: 'FAILURE',
                            webhookURL: env.WEBHOOK_URL
                cleanWs()
            }
        }
}