# Server Configuration
server:
  servlet:
    context-path: /api
  port: 8080

# Spring Configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wea-mysql:3306/wea?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=yes&characterEncoding=utf8&serverTimezone=Asia/Seoul
    username: weateam
    password: weateam0801

  jackson:
    time-zone: Asia/Seoul

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  jwt:
    secret: aa2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ